Hand csv.Sniffer() exactly one line of input
This fixes the following error caused by too much input:

    _csv.Error: Could not determine delimiter

https://stackoverflow.com/a/35757505/119527